# Generated by Django 4.2.2 on 2024-05-20 10:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('name', models.CharField(default='', max_length=45)),
                ('studentId', models.CharField(default='', max_length=45)),
                ('roomID', models.CharField(default='', max_length=1000)),
                ('isProfile', models.BooleanField(default=False)),
                ('isUserPref', models.BooleanField(default=False)),
                ('isRestricted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=45)),
                ('roomIntro', models.TextField(max_length=200, null=True)),
                ('date', models.CharField(max_length=45)),
                ('region', models.CharField(default='', max_length=45)),
                ('genre', models.IntegerField(default=0)),
                ('difficulty', models.FloatField(default=0)),
                ('fear', models.FloatField(default=0)),
                ('activity', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserPref',
            fields=[
                ('prefId', models.AutoField(primary_key=True, serialize=False)),
                ('Umbti', models.BooleanField(default=True)),
                ('UfirstLesson', models.BooleanField()),
                ('Usmoke', models.BooleanField()),
                ('UsleepHabit', models.BooleanField()),
                ('Ugrade', models.IntegerField()),
                ('UshareNeeds', models.BooleanField()),
                ('UinComm', models.BooleanField()),
                ('UheatSens', models.BooleanField()),
                ('UcoldSens', models.BooleanField()),
                ('UdrinkFreq', models.IntegerField()),
                ('Ucleanliness', models.IntegerField()),
                ('UnoiseSens', models.IntegerField()),
                ('UsleepSche', models.IntegerField()),
                ('UuserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprefs', to='Kiri_app.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportId', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('reporterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Kiri_app.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profileId', models.AutoField(primary_key=True, serialize=False)),
                ('Embti', models.BooleanField(default=True)),
                ('Smbti', models.BooleanField(default=True)),
                ('Tmbti', models.BooleanField(default=True)),
                ('Jmbti', models.BooleanField(default=True)),
                ('firstLesson', models.BooleanField()),
                ('smoke', models.BooleanField()),
                ('sleepHabit', models.BooleanField()),
                ('grade', models.IntegerField()),
                ('shareNeeds', models.BooleanField()),
                ('inComm', models.BooleanField()),
                ('heatSens', models.BooleanField()),
                ('coldSens', models.BooleanField()),
                ('drinkFreq', models.IntegerField()),
                ('cleanliness', models.IntegerField()),
                ('noiseSens', models.IntegerField()),
                ('sleepSche', models.IntegerField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='Kiri_app.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('matchId', models.AutoField(primary_key=True, serialize=False)),
                ('matchScore', models.FloatField()),
                ('matchStatus', models.CharField(default='pending', max_length=45)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updateAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchings', to='Kiri_app.appuser')),
                ('userId1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchings1', to='Kiri_app.appuser')),
                ('userId2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchings2', to='Kiri_app.appuser')),
                ('userId3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchings3', to='Kiri_app.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatID', models.IntegerField()),
                ('content', models.TextField()),
                ('createAT', models.DateTimeField()),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='Kiri_app.room')),
                ('senderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='Kiri_app.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('blockId', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('blockedId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockers', to='Kiri_app.appuser')),
                ('blockerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='Kiri_app.appuser')),
            ],
        ),
    ]
