# Generated by Django 4.2.2 on 2024-05-28 05:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('name', models.CharField(default='', max_length=45)),
                ('studentId', models.CharField(default='', max_length=45)),
                ('gender', models.CharField(default='', max_length=45)),
                ('isProfile', models.BooleanField(default=False)),
                ('isUserPref', models.BooleanField(default=False)),
                ('isRestricted', models.BooleanField(default=False)),
                ('matchStatus', models.CharField(default='pending', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('HistoryID', models.AutoField(primary_key=True, serialize=False)),
                ('userID2', models.IntegerField(default=0)),
                ('userID2name', models.CharField(default='', max_length=45)),
                ('AccessedTime', models.DateTimeField(auto_now_add=True)),
                ('recentMessage', models.TextField(default='')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_user', to='Kiri_app.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserPref',
            fields=[
                ('prefId', models.AutoField(primary_key=True, serialize=False)),
                ('UEmbti', models.IntegerField(default=0)),
                ('USmbti', models.IntegerField(default=0)),
                ('UTmbti', models.IntegerField(default=0)),
                ('UJmbti', models.IntegerField(default=0)),
                ('UfirstLesson', models.IntegerField()),
                ('Usmoke', models.IntegerField()),
                ('UsleepHabit', models.IntegerField()),
                ('Ugrade', models.IntegerField()),
                ('UshareNeeds', models.IntegerField()),
                ('UinComm', models.IntegerField()),
                ('UheatSens', models.IntegerField()),
                ('UcoldSens', models.IntegerField()),
                ('UdrinkFreq', models.IntegerField()),
                ('Ucleanliness', models.IntegerField()),
                ('UnoiseSens', models.IntegerField()),
                ('UsleepSche', models.IntegerField()),
                ('UupSche', models.IntegerField()),
                ('UuserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprefs', to='Kiri_app.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportId', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('reportedId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporters', to='Kiri_app.chatroom')),
                ('reporterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Kiri_app.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profileId', models.AutoField(primary_key=True, serialize=False)),
                ('Embti', models.IntegerField(default=0)),
                ('Smbti', models.IntegerField(default=0)),
                ('Tmbti', models.IntegerField(default=0)),
                ('Jmbti', models.IntegerField(default=0)),
                ('firstLesson', models.IntegerField()),
                ('smoke', models.IntegerField()),
                ('sleepHabit', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('shareNeeds', models.IntegerField()),
                ('inComm', models.IntegerField()),
                ('heatSens', models.IntegerField()),
                ('coldSens', models.IntegerField()),
                ('drinkFreq', models.IntegerField()),
                ('cleanliness', models.IntegerField()),
                ('noiseSens', models.IntegerField()),
                ('sleepSche', models.IntegerField()),
                ('upSche', models.IntegerField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='Kiri_app.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('matchId', models.AutoField(primary_key=True, serialize=False)),
                ('matchScore', models.FloatField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updateAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('userId1', models.IntegerField()),
                ('userId2', models.IntegerField()),
                ('userId3', models.IntegerField()),
                ('userId4', models.IntegerField()),
                ('userId5', models.IntegerField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchings', to='Kiri_app.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('messageID', models.AutoField(primary_key=True, serialize=False)),
                ('receiverID', models.IntegerField()),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('CHistoryID', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='Kiri_app.chatroom')),
                ('senderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='Kiri_app.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('blockId', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('blockedId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockers', to='Kiri_app.chatroom')),
                ('blockerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='Kiri_app.appuser')),
            ],
        ),
    ]
