# Generated by Django 4.2.2 on 2024-06-01 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kiri_app', '0002_rename_gender_appuser_gender_rename_id_appuser_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='ID',
            new_name='iD',
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='StudentID',
            new_name='studentID',
        ),
    ]
