# Generated by Django 4.2.2 on 2024-06-04 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kiri_app', '0004_rename_gender_appuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='matchScore',
        ),
    ]
