# Generated by Django 4.2.2 on 2024-06-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kiri_app', '0006_remove_match_createdat_remove_match_updateat'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='match',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
