# Generated by Django 4.2.2 on 2024-06-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kiri_app', '0007_match_createdat_match_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
