# Generated by Django 4.2.2 on 2024-06-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kiri_app', '0008_alter_match_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
