# Generated by Django 4.2.2 on 2024-06-06 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kiri_app', '0009_alter_block_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='blockedId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockers', to='Kiri_app.appuser'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reportedId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporters', to='Kiri_app.appuser'),
        ),
        migrations.AlterField(
            model_name='report',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
