# Generated by Django 4.2.2 on 2024-06-07 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kiri_app', '0010_alter_block_blockedid_alter_report_reportedid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='recentMessage',
        ),
    ]
