# Generated by Django 4.2.2 on 2024-06-08 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kiri_app', '0011_remove_chatroom_recentmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='AccessedTime',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='userID2name',
        ),
        migrations.AlterField(
            model_name='chat',
            name='receiverID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to='Kiri_app.appuser'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='userID2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_user2', to='Kiri_app.appuser'),
        ),
    ]
